#!/bin/bash
if [ ! -f ~/upgrade-system ]; then
	date > ~/upgrade-system
	echo 'Updating everything ...'

	if [ -x "$(command -v notify-send)" ]; then
		/usr/bin/notify-send "Updating everything ... " -i upgrade -t 5000 > /dev/null 2>&1
	fi

	packageUpdate0="Updating everything ... "
    /usr/bin/xterm  -bg black -fg white -fa 'Monospace' -title "$packageUpdate0" -fs 18 -e 'sleep 2s; wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz;sudo upgrade-system'
    rm ~/upgrade-system
fi
