#!/bin/bash
if [ ! -f ~/upgrade-system ]; then
        date > ~/upgrade-system
        echo 'Updating everything ... '
	/usr/bin/xterm -geometry 140x30 -fa 'Monospace' -fs 16 -e 'sudo upgrade-system'
        sleep 6s
        echo 'Turning off ... '
        rm ~/upgrade-system
        sudo poweroff
fi
