#!/bin/bash
if [ ! -f ~/upgrade-system ]; then
        date > ~/upgrade-system
        echo 'Updating everything ... '
        if [ -x "$(command -v notify-send)" ]; then
		/usr/bin/notify-send "Updating everything ... " -i upgrade -t 5000 > /dev/null 2>&1
	fi

        packageUpdate0="Updating everything ... "
        /usr/bin/xterm -fa 'Monospace' -title "$packageUpdate0" -fs 18 -e 'sleep 2s; wmctrl -r :ACTIVE: -b add,maximized_vert,maximized_horz;sudo upgrade-system'

        sleep 6s
        echo 'Turning off ... '
        rm ~/upgrade-system

	if [ -x "$(command -v notify-send)" ]; then
		/usr/bin/notify-send "Turning off ... " -i shutdown -t 5000 > /dev/null 2>&1
	fi

        sudo poweroff
fi
