#!/bin/sh
# Reset
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="X"


NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
        echo "${I_OK}    Statistics ...                                                              ${I_OK}";
        apk stats
        echo "${I_OK}    Updating ...                                                                ${I_OK}";
        apk update
        echo "${I_OK}    package list ...                                                            ${I_OK}";
        apk version
        echo "${I_OK}    Installing Updates ...                                                      ${I_OK}";
        apk upgrade
        echo "${I_OK}    Fixed ...                                                                   ${I_OK}";
        apk fix
        dates=$(date +'%d.%m.%Y %H:%M')
        echo "${I_OK}    updated system: ${dates}.                                           ${I_OK}";
        echo "";
        rm /var/cache/apk/* -v
fi
